export function truncate(str: string, maxLen: number): string {
  if (str.length <= maxLen) return str;
  return str.slice(0, maxLen - 3) + '...';
}

const CAVEAT_PREAMBLE = /Caveat: The messages below were generated by the user while running local commands\.\s*DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to\.?/gi;
const CAVEAT_MARKER = 'Caveat: The messages below were generated';

function stripCommandTags(text: string): string {
  if (!text.includes('<') && !text.includes(CAVEAT_MARKER)) return text;
  let out = text;
  out = out.replace(/<local-command-stdout>([\s\S]*?)<\/local-command-stdout>/g, '$1');
  out = out.replace(/<local-command-stderr>([\s\S]*?)<\/local-command-stderr>/g, '$1');
  out = out.replace(/<local-command-caveat>[\s\S]*?<\/local-command-caveat>/g, '');
  out = out.replace(/<command-name>([\s\S]*?)<\/command-name>/g, '$1');
  out = out.replace(/<command-message>[\s\S]*?<\/command-message>/g, '');
  out = out.replace(/<command-args>([\s\S]*?)<\/command-args>/g, (_m, args) => {
    const a = String(args).trim();
    return a.length > 0 ? ` ${a}` : '';
  });
  out = out.replace(/<[^>]+>/g, '');
  out = out.replace(CAVEAT_PREAMBLE, '');
  return out;
}

export function cleanMessageText(text: string): string {
  return stripCommandTags(text).replace(/\r/g, '').replace(/\s+/g, ' ').trim();
}

export function cleanMessageBlock(text: string): string {
  return stripCommandTags(text).replace(/\r/g, '').replace(/\n{3,}/g, '\n\n').trim();
}

export function isMeaningfulBranch(branch: string | undefined): branch is string {
  if (!branch) return false;
  const lower = branch.toLowerCase();
  return lower !== 'head' && lower !== 'detached';
}

export function formatDate(timestamp: number): string {
  const d = new Date(timestamp);
  return `${d.getMonth() + 1}/${d.getDate()}`;
}

const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

export function formatDateTime(timestamp: number): string {
  const d = new Date(timestamp);
  const minutes = String(d.getMinutes()).padStart(2, '0');
  return `${MONTHS[d.getMonth()]} ${d.getDate()} ${d.getHours()}:${minutes}`;
}

export function formatRelative(timestamp: number, now: number = Date.now()): string {
  const diff = Math.max(0, now - timestamp);
  const sec = Math.floor(diff / 1000);
  if (sec < 45) return 'now';
  const min = Math.floor(sec / 60);
  if (min < 60) return `${min}m ago`;
  const hr = Math.floor(min / 60);
  if (hr < 24) return `${hr}h ago`;
  const day = Math.floor(hr / 24);
  if (day < 30) return `${day}d ago`;
  const mo = Math.floor(day / 30);
  if (mo < 12) return `${mo}mo ago`;
  return `${Math.floor(mo / 12)}y ago`;
}

export function formatDuration(fromTs: number, toTs: number): string {
  const diff = Math.max(0, toTs - fromTs);
  const min = Math.floor(diff / 60000);
  if (min < 1) return '<1m';
  if (min < 60) return `${min}m`;
  const hr = Math.floor(min / 60);
  if (hr < 24) return `${hr}h`;
  const day = Math.floor(hr / 24);
  return `${day}d`;
}
